// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RickLocalization.Persistence;

namespace RickLocalization.Persistence.Migrations
{
    [DbContext(typeof(RickLocalizationContext))]
    [Migration("20210324235903_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("RickLocalization.Domain.Models.Dimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MortyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RickId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MortyId");

                    b.HasIndex("RickId");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("RickLocalization.Domain.Models.Morty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Morties");
                });

            modelBuilder.Entity("RickLocalization.Domain.Models.Rick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ricks");
                });

            modelBuilder.Entity("RickLocalization.Domain.Models.Dimension", b =>
                {
                    b.HasOne("RickLocalization.Domain.Models.Morty", "Morty")
                        .WithMany()
                        .HasForeignKey("MortyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RickLocalization.Domain.Models.Rick", "Rick")
                        .WithMany("DimensionsTraveller")
                        .HasForeignKey("RickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Morty");

                    b.Navigation("Rick");
                });

            modelBuilder.Entity("RickLocalization.Domain.Models.Rick", b =>
                {
                    b.Navigation("DimensionsTraveller");
                });
#pragma warning restore 612, 618
        }
    }
}
